// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "73a526ea-30b9-4aab-bfd5-d5523e9b7918");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1570205819);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1570205939);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1570250104);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1570250777);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1570250657);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1570205699);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1570119583);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1570206059);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 92478);
user_pref("browser.cache.disk.capacity", 768000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1570118713);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{238b0fff-ecfa-4192-8c01-223eb3d09983}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1570251906898");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1570253686898");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1570250092522");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1570253692522");
user_pref("browser.search.region", "BO");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1570228913");
user_pref("browser.slowStartup.averageTime", 12741);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190917224635");
user_pref("browser.startup.homepage_override.mstone", "69.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1570228911);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1570118718503");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "b69486f8b1064a778b99954fdd774330");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 02 Oct 2019 21:54:30 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1570205820);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190917224635");
user_pref("extensions.lastAppVersion", "69.0.1");
user_pref("extensions.lastPlatformVersion", "69.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{3fab01a2-42ef-4055-b9a6-6c90d55f1304}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e2a83bc9-91a5-4985-b19c-e9eca313cb4d\",\"fxmonitor@mozilla.org\":\"d4f5b78c-483c-4c41-9742-f9ac41c1fbb2\",\"screenshots@mozilla.org\":\"16302694-12a2-48b9-9029-4d70b113c540\",\"webcompat-reporter@mozilla.org\":\"7a3b55bb-6d4f-4923-af40-efec17395ac6\",\"webcompat@mozilla.org\":\"b84d2581-3bc8-493e-8269-8a601ffb0f61\",\"default-theme@mozilla.org\":\"654c4060-daa0-427b-a00d-51cba8dd532d\",\"google@search.mozilla.org\":\"34721905-6a00-43b9-a107-18a37da911e0\",\"amazondotcom@search.mozilla.org\":\"67cb8c92-56ba-475d-8dae-8403cb52019f\",\"bing@search.mozilla.org\":\"276af9d6-1af5-4c26-ad35-1f68c5c8c7c0\",\"ddg@search.mozilla.org\":\"0bac3c08-e36f-4235-af7d-e2b9626dfd36\",\"ebay@search.mozilla.org\":\"601c9a3c-7693-45c5-9c1d-ba6f5132b445\",\"twitter@search.mozilla.org\":\"ccbdc827-5617-4efb-9b1b-944ef47746cd\",\"wikipedia@search.mozilla.org\":\"b87a3ef8-910d-4f30-a295-4caa55ec02d3\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1570205666);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1570118749);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190917224635");
user_pref("media.gmp-manager.lastCheck", 1570205333);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1570205667);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "607abdaa-0513-46dc-8f07-2d91115f995e");
user_pref("security.sandbox.plugin.tempDirSuffix", "8801d57b-a827-456e-b392-6ec299a9794d");
user_pref("services.blocklist.pinning.checked", 1570205698);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1570213236062\"");
user_pref("services.settings.last_update_seconds", 1570228914);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1570228914);
user_pref("services.settings.main.cfr-fxa.last_check", 1570228914);
user_pref("services.settings.main.cfr.last_check", 1570228914);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1570228914);
user_pref("services.settings.main.hijack-blocklists.last_check", 1570228914);
user_pref("services.settings.main.language-dictionaries.last_check", 1570228914);
user_pref("services.settings.main.normandy-recipes.last_check", 1570228914);
user_pref("services.settings.main.sites-classification.last_check", 1570228914);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1570228914);
user_pref("services.settings.security.onecrl.checked", 1570205698);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1570205667);
user_pref("toolkit.startup.last_success", 1570228898);
user_pref("toolkit.telemetry.cachedClientID", "07a785d7-3c0e-476c-9b02-ce5ed77967d4");
user_pref("toolkit.telemetry.previousBuildID", "20190917224635");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
